from setuptools import setup, find_packages

setup(
    name="fzq_ai_agent",
    version="24.3.6",
    description="FZQ-AI Multi-Model Intelligence Analysis System",
    packages=find_packages(where="src"),
    package_dir={"": "src"},
    python_requires=">=3.10",
    install_requires=[
        "pydantic>=2.0",
        "fastapi>=0.111.0",
        "uvicorn[standard]>=0.30.0",
        "requests>=2.32.0",
        "aiohttp>=3.9.0",
        "feedparser>=6.0.0",
        "pyyaml>=6.0",
        "python-dotenv>=1.0.0",
        "openai>=1.30.0",
        "google-genai>=0.1.0",
        "streamlit>=1.35.0",
        "plotly>=5.22.0",
        "networkx>=3.3",
        "matplotlib>=3.9.0",
        "numpy>=1.26.0",
        "langdetect>=1.0.9",
        "redis>=5.0.0",
        "jinja2>=3.1.0",
        "sentence-transformers>=2.2.0",
    ],
    extras_require={
        "dev": [
            "pytest>=8.2.0",
            "pytest-asyncio>=0.23.0",
            "pytest-cov>=5.0.0",
            "black>=24.4.0",
            "ruff>=0.4.0",
            "mypy>=1.10.0",
            "bandit[toml]>=1.7.0",
            "pre-commit>=3.7.0",
        ],
    },
)
