"""
fzq_ai/agent/autonomy_agent.py — v4.5 Autonomous Intelligence Agent

Core autonomous loop: think → plan → act → sleep → repeat.
Uses LLM for reasoning about what to monitor next.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional
import json, logging, time

from fzq_ai.store.intel_store import IntelStore

logger = logging.getLogger(__name__)


@dataclass
class TaskPlan:
    """Structured task plan generated by think()."""
    tasks: List[Dict[str, str]] = field(default_factory=list)
    reasoning: str = ""


class AutonomyAgent:
    """
    v4.5 Autonomous Intelligence Agent.

    think() — LLM-based reasoning about what to do next
    plan()  — Structured task generation
    act()   — Execute tasks via orchestrator
    loop()  — Main autonomous cycle
    """

    def __init__(self, store: IntelStore, orchestrator: Any = None):
        self._store = store
        self._orchestrator = orchestrator
        self._state: Dict[str, Any] = {
            "last_run": 0.0,
            "cycle_count": 0,
            "alerts_triggered": 0,
        }

    # ── think() — LLM 思考 ──

    def think(self) -> str:
        """
        Analyze current trends and decide next actions.

        Uses trend data from IntelStore + LLM reasoning.
        Returns raw LLM reasoning text.
        """
        trends_summary = self._gather_trends()
        prompt = (
            "You are an autonomous intelligence analyst for FZQ-AI.\n\n"
            f"Current trends and data:\n{trends_summary}\n\n"
            "Based on the above, what tasks should be executed next?\n"
            "Respond in JSON format:\n"
            '{"tasks": [{"type": "scenario|report|watchlist", "name": "..."}], '
            '"reasoning": "..."}'
        )

        # Try LLM call, fall back to rules if no LLM available
        try:
            from fzq_ai.llm.llm_router import LLMRouter
            router = LLMRouter()
            # ⚠️ 注意：此方法在异步环境中会崩溃（RuntimeError）。
            # 调用方应在异步上下文中直接 await router.run(prompt) 或使用 asyncio.run() 在外部管理。
            raw = asyncio.run(router.run(prompt))
            return raw
        except RuntimeError as e:
            if "cannot be called from a running event loop" in str(e):
                logger.warning("asyncio.run() failed in running event loop, falling back to rule-based")
            return self._rule_based_think(trends_summary)
        except Exception:
            return self._rule_based_think(trends_summary)

    def _rule_based_think(self, summary: str) -> str:
        """Fallback: rule-based task generation."""
        tasks = [
            {"type": "scenario", "name": "daily_global_risk"},
            {"type": "report", "name": "global risk"},
        ]
        result = {"tasks": tasks, "reasoning": "Rule-based: daily scan + report"}
        return json.dumps(result, ensure_ascii=False)

    def _gather_trends(self) -> str:
        """Collect recent trends from data store."""
        lines = ["- Cycle: " + str(self._state["cycle_count"])]
        try:
            topics = ["global conflict", "US election", "energy market"]
            for t in topics:
                records = self._store.load_latest(t, limit=1)
                count = len(records[0].bundle.articles) if records else 0
                lines.append(f"- {t}: {count} articles (latest)")
        except Exception:
            pass
        return "\n".join(lines)

    # ── plan() — 规划 ──

    def plan(self, think_output: str) -> TaskPlan:
        """
        Parse LLM output into structured TaskPlan.

        Args:
            think_output: Raw text from think() (JSON or plain text)

        Returns:
            TaskPlan with parsed tasks
        """
        plan = TaskPlan()
        try:
            # Try to extract JSON
            text = think_output.strip()
            if "```" in text:
                # Extract from code block
                start = text.find("{")
                end = text.rfind("}") + 1
                text = text[start:end] if start >= 0 else text
            data = json.loads(text)
            plan.tasks = data.get("tasks", [])
            plan.reasoning = data.get("reasoning", "")
        except (json.JSONDecodeError, ValueError):
            # Fallback: keyword-based planning
            plan.tasks = [{"type": "scenario", "name": "daily_global_risk"}]
            plan.reasoning = "Default daily scan (JSON parse failed)"
        return plan

    # ── act() — 执行 ──

    def act(self, plan: TaskPlan) -> Dict[str, Any]:
        """
        Execute the task plan via orchestrator.

        Args:
            plan: Structured TaskPlan from plan()

        Returns:
            Results dict keyed by task name
        """
        results: Dict[str, Any] = {}

        if not self._orchestrator:
            logger.warning("No orchestrator set — act() is no-op")
            return results

        for task in plan.tasks:
            task_type = task.get("type", "")
            task_name = task.get("name", "")

            try:
                if task_type == "scenario" and task_name:
                    if hasattr(self._orchestrator, "run_scenario"):
                        results[task_name] = self._orchestrator.run_scenario(
                            task_name
                        )
                    else:
                        results[task_name] = self._orchestrator.run_nl(
                            task_name.replace("_", " ")
                        )

                elif task_type == "report":
                    from fzq_ai.agents.report_agent import ReportAgent
                    agent = ReportAgent(store=self._store)
                    results[task_name] = agent.generate_markdown_report(task_name)

                elif task_type == "watchlist":
                    from fzq_ai.agents.watchlist_agent import WatchlistAgent
                    agent = WatchlistAgent(orchestrator=self._orchestrator)
                    results["watchlist"] = agent.run_once()

            except Exception as e:
                logger.warning(f"Task {task_name} failed: {e}")
                results[task_name] = {"error": str(e)}

        return results

    # ── loop() — 主循环 ──

    def loop(self, interval_seconds: int = 1800, max_cycles: int = 0) -> None:
        """
        Main autonomous loop.

        Args:
            interval_seconds: Sleep time between cycles (default 30 min)
            max_cycles: Max cycles to run (0 = infinite)
        """
        cycle = 0
        while max_cycles == 0 or cycle < max_cycles:
            cycle += 1
            self._state["cycle_count"] = cycle
            self._state["last_run"] = time.time()

            logger.info(f"=== AutonomyAgent cycle {cycle} ===")

            # think
            think_output = self.think()

            # plan
            plan = self.plan(think_output)

            # act
            results = self.act(plan)
            logger.info(f"Cycle {cycle} results: {list(results.keys())}")

            if max_cycles != 1:
                time.sleep(interval_seconds)

    # ── Lifecycle ──

    def start(self) -> None:
        """Start autonomous operation (non-blocking note)."""
        self._state["started"] = time.time()
        logger.info("AutonomyAgent started")

    def stop(self) -> None:
        """Stop autonomous operation."""
        self._state["stopped"] = time.time()
        logger.info("AutonomyAgent stopped")

    @property
    def status(self) -> Dict[str, Any]:
        return dict(self._state)
