"""
fzq_ai/agent/report_agent.py — v3.0 Report Agent (spec-compliant)
Generates structured Markdown intelligence reports from IntelStore data.
"""

from __future__ import annotations
from datetime import datetime
from typing import Any, Dict, List, Optional

from fzq_ai.store.intel_store import IntelStore, IntelRecord

class ReportAgent:
    """

    """

    def __init__(self, store: Optional[IntelStore] = None):
        self._store = store or IntelStore()

    def generate_markdown_report(self, topic: str, runs: int = 3) -> str:
        """
        Generate a Markdown intelligence report for a topic.

        """
        records = self._store.load_latest(topic, limit=runs)
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        if not records:
            return self._empty_report(topic, now)

        # Gather data from all records

        for r in records:
            if r.bundle and r.bundle.articles:

        regions_seen = set(a.region for a in all_articles if a.region)
        risk_scores = [getattr(a, "risk_level", 0) or 0 for a in all_articles]
        avg_risk = sum(risk_scores) / max(len(risk_scores), 1)

        # Build report sections
            f"# FZQ-AI Intelligence Report — {topic}",
            "",
            "",
            "---",
            "",
            "## 1. Executive Summary",
            "",
            "",
            "---",
            "",
            "## 2. Cross-Region News Snapshot",
            "",

        for a in all_articles:

        for region, arts in sorted(region_articles.items()):
            sources = set(a.source_name for a in arts if a.source_name)
            lines.append(f"### {region.title()}")
            lines.append(f"- Sources: {', '.join(list(sources)[:5])}")
            lines.append(f"- Articles: {len(arts)}")
            for a in arts[:3]:

            "---",
            "",
            "## 3. Risk Matrix",
            "",
            "| Dimension | Level (1-5) | Notes |",
            "|-----------|-------------|-------|",
            "| Economic  | — | — |",
            "| Military  | — | — |",
            "| Social    | — | — |",
            "| Tech      | — | — |",
            "",
            "---",
            "",
            "## 4. Sample Articles",
            "",

        for a in all_articles[:10]:
            lines.append(f"### {title[:100]}")
            lines.append(f"- Source: {source} ({region})")
            if url:

            "---",
            f"*Generated by FZQ-AI v3.0 ReportAgent for topic: {topic}*",
        return "\n".join(lines)

    def _empty_report(self, topic: str, now: str) -> str:
        return "\n".join([
            f"# FZQ-AI Intelligence Report — {topic}",
            "",
            "No data available for this topic. Run a pipeline first.",

    def save_report(self, content: str, filename: Optional[str] = None) -> str:
        import os
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path
