"""
fzq_ai/agent/report_agent.py — v3.0 Report Agent (spec-compliant)
Generates structured Markdown intelligence reports from IntelStore data.
"""

from __future__ import annotations
from datetime import datetime
from typing import Any, Dict, List, Optional

from fzq_ai.store.intel_store import IntelStore, IntelRecord


class ReportAgent:
    """
    v3.0 — Intelligence report generator.

    Pulls data from IntelStore and fills a structured Markdown template.
    """

    def __init__(self, store: Optional[IntelStore] = None):
        self._store = store or IntelStore()

    def generate_markdown_report(self, topic: str, runs: int = 3) -> str:
        """
        Generate a Markdown intelligence report for a topic.

        Args:
            topic: Topic to report on
            runs: Number of historical runs to include

        Returns:
            Markdown string
        """
        records = self._store.load_latest(topic, limit=runs)
        now = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

        if not records:
            return self._empty_report(topic, now)

        # Gather data from all records
        all_articles = []
        provider_snapshots = []
        run_ids = []

        for r in records:
            run_ids.append(r.run_id[:8])
            provider_snapshots.append(r.provider_snapshot)
            if r.bundle and r.bundle.articles:
                all_articles.extend(r.bundle.articles)

        regions_seen = set(a.region for a in all_articles if a.region)
        risk_scores = [getattr(a, "risk_level", 0) or 0 for a in all_articles]
        avg_risk = sum(risk_scores) / max(len(risk_scores), 1)

        # Build report sections
        lines = [
            f"# FZQ-AI Intelligence Report — {topic}",
            "",
            f"- **Generated:** {now}",
            f"- **Runs included:** {', '.join(run_ids)}",
            f"- **Articles analyzed:** {len(all_articles)}",
            "",
            "---",
            "",
            "## 1. Executive Summary",
            "",
            f"- **Overall Risk Level (1-5):** {min(round(avg_risk, 1), 5.0)}",
            f"- **Regions covered:** {len(regions_seen)} ({', '.join(sorted(regions_seen)[:8])})",
            f"- **Key Takeaway:** Automated analysis of {len(all_articles)} articles across {len(records)} pipeline runs.",
            "",
            "---",
            "",
            "## 2. Cross-Region News Snapshot",
            "",
        ]

        region_articles: Dict[str, List] = {}
        for a in all_articles:
            r = a.region or "other"
            region_articles.setdefault(r, []).append(a)

        for region, arts in sorted(region_articles.items()):
            sources = set(a.source_name for a in arts if a.source_name)
            lines.append(f"### {region.title()}")
            lines.append(f"- Sources: {', '.join(list(sources)[:5])}")
            lines.append(f"- Articles: {len(arts)}")
            for a in arts[:3]:
                t = a.title_original or "N/A"
                lines.append(f"  - {t[:100]}")
            lines.append("")

        lines.extend([
            "---",
            "",
            "## 3. Risk Matrix",
            "",
            "| Dimension | Level (1-5) | Notes |",
            "|-----------|-------------|-------|",
            f"| Political | {min(round(avg_risk, 0), 5.0):.0f} | Auto-scored |",
            "| Economic  | — | — |",
            "| Military  | — | — |",
            "| Social    | — | — |",
            "| Tech      | — | — |",
            "",
            "---",
            "",
            "## 4. Sample Articles",
            "",
        ])

        for a in all_articles[:10]:
            title = a.title_original or "N/A"
            source = a.source_name or "?"
            region = a.region or "?"
            url = a.url or ""
            lines.append(f"### {title[:100]}")
            lines.append(f"- Source: {source} ({region})")
            if url:
                lines.append(f"- URL: {url}")
            lines.append("")

        lines.extend([
            "---",
            f"*Generated by FZQ-AI v3.0 ReportAgent for topic: {topic}*",
        ])
        return "\n".join(lines)

    def _empty_report(self, topic: str, now: str) -> str:
        return "\n".join([
            f"# FZQ-AI Intelligence Report — {topic}",
            f"- **Generated:** {now}",
            "",
            "No data available for this topic. Run a pipeline first.",
        ])

    def save_report(self, content: str, filename: Optional[str] = None) -> str:
        import os
        os.makedirs("reports", exist_ok=True)
        fname = filename or f"report-{datetime.now().strftime('%Y%m%d-%H%M')}.md"
        path = os.path.join("reports", fname)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        return path
