"""src/fzq_ai/minimax/phase2/feedback_models.py

Pydantic models for Minimax Phase 2 structural feedback reports.

All output is JSON-serializable (R6). Field names follow FZQ-AI schema
conventions. Scores are 0-100 floats.
"""
from __future__ import annotations
import datetime
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field, field_validator


class StructuralFeedback(BaseModel):
    """Phase 2 output: structural feedback report (read-only, no code).

    Generated by `MinimaxFeedbackEngine.generate()` and routed by
    `MinimaxFeedbackRouter.route()`. Never contains code changes.
    """

    source: str = Field(default="minimax_phase2", description="Producer identifier")
    target_models: List[str] = Field(
        default_factory=lambda: ["glm", "deepseek", "doubao", "kimi", "qwen"],
        description="Downstream/upstream targets this feedback addresses",
    )

    # Field-level issues (R3: only report, never invent fields)
    missing_fields: List[str] = Field(
        default_factory=list,
        description="Top-level or nested fields absent from original input",
    )
    type_repairs: List[str] = Field(
        default_factory=list,
        description="Fields that were coerced to canonical type (e.g. str→list)",
    )
    risk_repairs: List[str] = Field(
        default_factory=list,
        description="Risk sub-categories that required type/structure repair",
    )
    order_repairs: List[str] = Field(
        default_factory=list,
        description="Fields that were re-ordered to canonical sequence",
    )

    # Scores (0-100) — R5: structural feedback only
    consistency_score: float = Field(
        default=0.0,
        description="Field completeness 0-100; 100 = all canonical fields populated",
    )
    risk_score: float = Field(
        default=0.0,
        description="Risk structure completeness 0-100; 100 = all 5 categories populated",
    )

    # Suggestions (R1: no code; R5: structural only)
    suggestions: List[str] = Field(
        default_factory=list,
        description="Structural suggestions (e.g. 'Add risks.economic to DeepSeek prompt'); never code",
    )

    # Metadata
    trace_id: str = Field(
        default_factory=lambda: str(__import__("uuid").uuid4()),
        description="Correlates with parent pipeline trace_id",
    )
    generated_at: str = Field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc).isoformat(),
        description="ISO 8601 UTC timestamp",
    )

    @field_validator("consistency_score", "risk_score")
    @classmethod
    def _validate_score_range(cls, v: float) -> float:
        """Scores must be in [0.0, 100.0]."""
        if not (0.0 <= v <= 100.0):
            raise ValueError(f"Score must be in [0.0, 100.0], got {v}")
        return round(v, 2)


class RoutedFeedback(BaseModel):
    """Phase 2 router output: per-target feedback slices.

    Each slice is itself a structural feedback dict (subset of StructuralFeedback).
    """

    target: str = Field(description="Target model name (glm/deepseek/doubao/kimi/qwen/ds)")
    issues: List[str] = Field(default_factory=list, description="Target-specific issues")
    suggestions: List[str] = Field(default_factory=list, description="Target-specific suggestions")
    priority: str = Field(default="medium", description="low | medium | high")
    requires_action: bool = Field(default=False, description="True if target should react")


class CommitDecision(BaseModel):
    """Phase 2 commit decision: can Minimax self-commit, or does it need DS execution book?"""

    minimax_can_commit: bool = Field(
        description="True if all feedback is structural (Phase 2 default)",
    )
    reason: str = Field(description="Human-readable justification")
    requires_ds_execution_book: bool = Field(
        default=False,
        description="True if feedback indicates code/schema/pipeline/agent changes needed",
    )
    ds_tasks: List[str] = Field(
        default_factory=list,
        description="If requires_ds_execution_book, list of tasks for DS to execute",
    )